export = (
  <ask args={<list />}>
    <call
      name="test"
      args={
        <list>
          {"equals"}
          <fun args={<list />} returns={<ref name="any" />}>
            <call
              name="toBe"
              args={
                <list>
                  <call
                    name="expect"
                    args={
                      <list>
                        <call
                          name="=="
                          args={
                            <list>
                              {2}
                              {2}
                            </list>
                          }
                          isOperator={true}
                        />
                      </list>
                    }
                  />
                  <call name="true" args={<list />} />
                </list>
              }
            />
            <call
              name="toBe"
              args={
                <list>
                  <call
                    name="expect"
                    args={
                      <list>
                        <call
                          name="=="
                          args={
                            <list>
                              {2}
                              {3}
                            </list>
                          }
                          isOperator={true}
                        />
                      </list>
                    }
                  />
                  <call name="false" args={<list />} />
                </list>
              }
            />
            <call
              name="toBe"
              args={
                <list>
                  <call
                    name="expect"
                    args={
                      <list>
                        <call
                          name="=="
                          args={
                            <list>
                              {1.3}
                              {1.3}
                            </list>
                          }
                          isOperator={true}
                        />
                      </list>
                    }
                  />
                  <call name="true" args={<list />} />
                </list>
              }
            />
            <call
              name="toBe"
              args={
                <list>
                  <call
                    name="expect"
                    args={
                      <list>
                        <call
                          name="=="
                          args={
                            <list>
                              {1.3}
                              {2.3}
                            </list>
                          }
                          isOperator={true}
                        />
                      </list>
                    }
                  />
                  <call name="false" args={<list />} />
                </list>
              }
            />
            <call
              name="toBe"
              args={
                <list>
                  <call
                    name="expect"
                    args={
                      <list>
                        <call
                          name="=="
                          args={
                            <list>
                              {"a"}
                              {"a"}
                            </list>
                          }
                          isOperator={true}
                        />
                      </list>
                    }
                  />
                  <call name="true" args={<list />} />
                </list>
              }
            />
            <call
              name="toBe"
              args={
                <list>
                  <call
                    name="expect"
                    args={
                      <list>
                        <call
                          name="=="
                          args={
                            <list>
                              {"a"}
                              {"b"}
                            </list>
                          }
                          isOperator={true}
                        />
                      </list>
                    }
                  />
                  <call name="false" args={<list />} />
                </list>
              }
            />
            <call
              name="toBe"
              args={
                <list>
                  <call
                    name="expect"
                    args={
                      <list>
                        <call
                          name="=="
                          args={
                            <list>
                              <call name="false" args={<list />} />
                              {""}
                            </list>
                          }
                          isOperator={true}
                        />
                      </list>
                    }
                  />
                  <call name="false" args={<list />} />
                </list>
              }
            />
            <call
              name="toBe"
              args={
                <list>
                  <call
                    name="expect"
                    args={
                      <list>
                        <call
                          name="=="
                          args={
                            <list>
                              <call name="false" args={<list />} />
                              {"[]"}
                            </list>
                          }
                          isOperator={true}
                        />
                      </list>
                    }
                  />
                  <call name="false" args={<list />} />
                </list>
              }
            />
            <call
              name="toBe"
              args={
                <list>
                  <call
                    name="expect"
                    args={
                      <list>
                        <call
                          name="=="
                          args={
                            <list>
                              <call name="false" args={<list />} />
                              {0}
                            </list>
                          }
                          isOperator={true}
                        />
                      </list>
                    }
                  />
                  <call name="false" args={<list />} />
                </list>
              }
            />
            <call
              name="toBe"
              args={
                <list>
                  <call
                    name="expect"
                    args={
                      <list>
                        <call
                          name="=="
                          args={
                            <list>
                              {1}
                              {"1"}
                            </list>
                          }
                          isOperator={true}
                        />
                      </list>
                    }
                  />
                  <call name="false" args={<list />} />
                </list>
              }
            />
          </fun>
        </list>
      }
    />
  </ask>
);
