export = (
  <ask args={<list />}>
    <call
      name="+"
      args={
        <list>
          <call
            name="-"
            args={
              <list>
                <call
                  name="+"
                  args={
                    <list>
                      <call
                        name="-"
                        args={
                          <list>
                            <call
                              name="+"
                              args={
                                <list>
                                  <call
                                    name="-"
                                    args={
                                      <list>
                                        <call
                                          name="+"
                                          args={
                                            <list>
                                              {1}
                                              {2}
                                            </list>
                                          }
                                          isOperator={true}
                                        />
                                        {3}
                                      </list>
                                    }
                                    isOperator={true}
                                  />
                                  {4}
                                </list>
                              }
                              isOperator={true}
                            />
                            {5}
                          </list>
                        }
                        isOperator={true}
                      />
                      {6}
                    </list>
                  }
                  isOperator={true}
                />
                {7}
              </list>
            }
            isOperator={true}
          />
          {8}
        </list>
      }
      isOperator={true}
    />
  </ask>
);
