export = (
  <ask args={<list />}>
    <const
      name="covid"
      type={<ref name="any" />}
      value={
        <list>
          <struct>
            {"country"}
            {"USA"}
            {"newInfected"}
            {69128}
            {"newDeaths"}
            {1047}
            {"newRecovered"}
            {19342}
          </struct>
          <struct>
            {"country"}
            {"Spain"}
            {"newInfected"}
            {13598}
            {"newDeaths"}
            {217}
            {"newRecovered"}
            {578}
          </struct>
          <struct>
            {"country"}
            {"Russia"}
            {"newInfected"}
            {1551}
            {"newDeaths"}
            {93}
            {"newRecovered"}
            {178}
          </struct>
          <struct>
            {"country"}
            {"Italy"}
            {"newInfected"}
            {992}
            {"newDeaths"}
            {262}
            {"newRecovered"}
            {688}
          </struct>
          <struct>
            {"country"}
            {"UK"}
            {"newInfected"}
            {3687}
            {"newDeaths"}
            {428}
            {"newRecovered"}
            {555}
          </struct>
        </list>
      }
    />
    <call
      name="find"
      args={
        <list>
          <ref name="covid" />
          <fun
            args={
              <list>
                <list>
                  {"c"}
                  <ref name="any" />
                </list>
              </list>
            }
            returns={<ref name="any" />}
          >
            <return
              value={
                <call
                  name="&&"
                  args={
                    <list>
                      <call
                        name="moreThan"
                        args={
                          <list>
                            <call
                              name="at"
                              args={
                                <list>
                                  <ref name="c" />
                                  {"newDeaths"}
                                </list>
                              }
                            />
                            {200}
                          </list>
                        }
                      />
                      <call
                        name="lessThan"
                        args={
                          <list>
                            <call
                              name="at"
                              args={
                                <list>
                                  <ref name="c" />
                                  {"newDeaths"}
                                </list>
                              }
                            />
                            {1000}
                          </list>
                        }
                      />
                    </list>
                  }
                  isOperator={true}
                />
              }
            />
          </fun>
        </list>
      }
    />
  </ask>
);
