export = (
  <list>
    <struct>
      {"country"}
      {"USA"}
      {"newInfected"}
      {69128}
      {"newDeaths"}
      {1047}
      {"newRecovered"}
      {19342}
    </struct>
    <struct>
      {"country"}
      {"Spain"}
      {"newInfected"}
      {13598}
      {"newDeaths"}
      {217}
      {"newRecovered"}
      {578}
    </struct>
    <struct>
      {"country"}
      {"Russia"}
      {"newInfected"}
      {1551}
      {"newDeaths"}
      {93}
      {"newRecovered"}
      {178}
    </struct>
    <struct>
      {"country"}
      {"Italy"}
      {"newInfected"}
      {992}
      {"newDeaths"}
      {262}
      {"newRecovered"}
      {688}
    </struct>
    <struct>
      {"country"}
      {"UK"}
      {"newInfected"}
      {3687}
      {"newDeaths"}
      {428}
      {"newRecovered"}
      {19342}
    </struct>
  </list>
);
