export = (
  <ask args={<list />}>
    <let
      name="revPerClient"
      type={<ref name="any" />}
      value={
        <struct>
          {"A"}
          {136}
          {"B"}
          {426}
          {"C"}
          {133}
          {"D"}
          {35}
          {"E"}
          {246}
          {"F"}
          {446}
          {"G"}
          {53}
        </struct>
      }
    />
    <let
      name="complexObject"
      type={<ref name="any" />}
      value={
        <struct>
          {"countries"}
          <list>
            <struct>
              {"name"}
              {"Poland"}
              {"population"}
              {"38M"}
            </struct>
            <struct>
              {"name"}
              {"Germany"}
              {"population"}
              {"80M"}
            </struct>
            <struct>
              {"name"}
              {"Greece"}
              {"population"}
              {"10M"}
            </struct>
          </list>
        </struct>
      }
    />
    <struct>
      {"elementByExactPath"}
      <call
        name="jsonPath"
        args={
          <list>
            <ref name="revPerClient" />
            {"$.A"}
          </list>
        }
      />
      {"countryNames"}
      <call
        name="jsonPath"
        args={
          <list>
            <ref name="complexObject" />
            {"$.countries[*].name"}
          </list>
        }
      />
      {"populationOfGermany"}
      <call
        name="jsonPath"
        args={
          <list>
            <ref name="complexObject" />
            {'$.countries[?(@.name=="Germany")].population'}
          </list>
        }
      />
    </struct>
  </ask>
);
